//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebModels.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessAdminSites.
        /// </summary>
        public static string AccessAdminSites {
            get {
                return ResourceManager.GetString("AccessAdminSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessKey.
        /// </summary>
        public static string AccessKey {
            get {
                return ResourceManager.GetString("AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessLogs.
        /// </summary>
        public static string AccessLogs {
            get {
                return ResourceManager.GetString("AccessLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessWebModules.
        /// </summary>
        public static string AccessWebModules {
            get {
                return ResourceManager.GetString("AccessWebModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveType.
        /// </summary>
        public static string ActiveType {
            get {
                return ResourceManager.GetString("ActiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminSite.
        /// </summary>
        public static string AdminSite {
            get {
                return ResourceManager.GetString("AdminSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Key.
        /// </summary>
        public static string AdminSiteAccessKey {
            get {
                return ResourceManager.GetString("AdminSiteAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AdminSiteDescription {
            get {
                return ResourceManager.GetString("AdminSiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site ID.
        /// </summary>
        public static string AdminSiteID {
            get {
                return ResourceManager.GetString("AdminSiteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string AdminSiteParent {
            get {
                return ResourceManager.GetString("AdminSiteParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string AdminSiteTitle {
            get {
                return ResourceManager.GetString("AdminSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site URL.
        /// </summary>
        public static string AdminSiteUrl {
            get {
                return ResourceManager.GetString("AdminSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport code.
        /// </summary>
        public static string AirportCode {
            get {
                return ResourceManager.GetString("AirportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport name.
        /// </summary>
        public static string AirportName {
            get {
                return ResourceManager.GetString("AirportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assizes.
        /// </summary>
        public static string Assizes {
            get {
                return ResourceManager.GetString("Assizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackMoneyCustomer.
        /// </summary>
        public static string BackMoneyCustomer {
            get {
                return ResourceManager.GetString("BackMoneyCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bday.
        /// </summary>
        public static string Bday {
            get {
                return ResourceManager.GetString("Bday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillID.
        /// </summary>
        public static string BillID {
            get {
                return ResourceManager.GetString("BillID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillIDRequired.
        /// </summary>
        public static string BillIDRequired {
            get {
                return ResourceManager.GetString("BillIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox.
        /// </summary>
        public static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Color.
        /// </summary>
        public static string CodeColor {
            get {
                return ResourceManager.GetString("CodeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommodityID.
        /// </summary>
        public static string CommodityID {
            get {
                return ResourceManager.GetString("CommodityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommodityIdExists.
        /// </summary>
        public static string CommodityIdExists {
            get {
                return ResourceManager.GetString("CommodityIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommodityName.
        /// </summary>
        public static string CommodityName {
            get {
                return ResourceManager.GetString("CommodityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentType.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentTypeID.
        /// </summary>
        public static string ContentTypeID {
            get {
                return ResourceManager.GetString("ContentTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CostPrice.
        /// </summary>
        public static string CostPrice {
            get {
                return ResourceManager.GetString("CostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPNCT.
        /// </summary>
        public static string CostReturnCompanyCode {
            get {
                return ResourceManager.GetString("CostReturnCompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country ID.
        /// </summary>
        public static string CountryID {
            get {
                return ResourceManager.GetString("CountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedAt.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerAddress.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerCode.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerID.
        /// </summary>
        public static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerIdExists.
        /// </summary>
        public static string CustomerIdExists {
            get {
                return ResourceManager.GetString("CustomerIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerName.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerPayment.
        /// </summary>
        public static string CustomerPayment {
            get {
                return ResourceManager.GetString("CustomerPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerRequired.
        /// </summary>
        public static string CustomerRequired {
            get {
                return ResourceManager.GetString("CustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPCSKH.
        /// </summary>
        public static string CustomerServiceCode {
            get {
                return ResourceManager.GetString("CustomerServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable.
        /// </summary>
        public static string DataTable {
            get {
                return ResourceManager.GetString("DataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateKey.
        /// </summary>
        public static string DateKey {
            get {
                return ResourceManager.GetString("DateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateRequired.
        /// </summary>
        public static string DateRequired {
            get {
                return ResourceManager.GetString("DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTimeKey.
        /// </summary>
        public static string DateTimeKey {
            get {
                return ResourceManager.GetString("DateTimeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DealCode.
        /// </summary>
        public static string DealCode {
            get {
                return ResourceManager.GetString("DealCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DealCodeExists.
        /// </summary>
        public static string DealCodeExists {
            get {
                return ResourceManager.GetString("DealCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DealCodeNotValid.
        /// </summary>
        public static string DealCodeNotValid {
            get {
                return ResourceManager.GetString("DealCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DealCodeRequired.
        /// </summary>
        public static string DealCodeRequired {
            get {
                return ResourceManager.GetString("DealCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailNote.
        /// </summary>
        public static string DetailNote {
            get {
                return ResourceManager.GetString("DetailNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscountAmount.
        /// </summary>
        public static string DiscountAmount {
            get {
                return ResourceManager.GetString("DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPDT.
        /// </summary>
        public static string ElectricPhoneCode {
            get {
                return ResourceManager.GetString("ElectricPhoneCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is not a valid email address.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorPrice.
        /// </summary>
        public static string ErrorPrice {
            get {
                return ResourceManager.GetString("ErrorPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportExcel.
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreightCharge.
        /// </summary>
        public static string FreightCharge {
            get {
                return ResourceManager.GetString("FreightCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreightPrice.
        /// </summary>
        public static string FreightPrice {
            get {
                return ResourceManager.GetString("FreightPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionName.
        /// </summary>
        public static string FunctionName {
            get {
                return ResourceManager.GetString("FunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexLayout.
        /// </summary>
        public static string IndexLayout {
            get {
                return ResourceManager.GetString("IndexLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexView.
        /// </summary>
        public static string IndexView {
            get {
                return ResourceManager.GetString("IndexView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InformationCost.
        /// </summary>
        public static string InformationCost {
            get {
                return ResourceManager.GetString("InformationCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputComboboxProductID.
        /// </summary>
        public static string InputComboboxProductID {
            get {
                return ResourceManager.GetString("InputComboboxProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputNumber.
        /// </summary>
        public static string InputNumber {
            get {
                return ResourceManager.GetString("InputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputPrice.
        /// </summary>
        public static string InputPrice {
            get {
                return ResourceManager.GetString("InputPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntMoney1000NotValid.
        /// </summary>
        public static string IntMoney1000NotValid {
            get {
                return ResourceManager.GetString("IntMoney1000NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceCodeExists.
        /// </summary>
        public static string InvoiceCodeExists {
            get {
                return ResourceManager.GetString("InvoiceCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceCodeNotValid.
        /// </summary>
        public static string InvoiceCodeNotValid {
            get {
                return ResourceManager.GetString("InvoiceCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceManageNotValid.
        /// </summary>
        public static string InvoiceManageNotValid {
            get {
                return ResourceManager.GetString("InvoiceManageNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLock.
        /// </summary>
        public static string IsLock {
            get {
                return ResourceManager.GetString("IsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO Code.
        /// </summary>
        public static string IsoCode {
            get {
                return ResourceManager.GetString("IsoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPNC.
        /// </summary>
        public static string LaborCode {
            get {
                return ResourceManager.GetString("LaborCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link video.
        /// </summary>
        public static string LinkVideo {
            get {
                return ResourceManager.GetString("LinkVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriage.
        /// </summary>
        public static string Marriage {
            get {
                return ResourceManager.GetString("Marriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaDescription.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaKeywords.
        /// </summary>
        public static string MetaKeywords {
            get {
                return ResourceManager.GetString("MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTitle.
        /// </summary>
        public static string MetaTitle {
            get {
                return ResourceManager.GetString("MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoneyDebt.
        /// </summary>
        public static string MoneyDebt {
            get {
                return ResourceManager.GetString("MoneyDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoneyRequired.
        /// </summary>
        public static string MoneyRequired {
            get {
                return ResourceManager.GetString("MoneyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberArises.
        /// </summary>
        public static string NumberArises {
            get {
                return ResourceManager.GetString("NumberArises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberArisesExists.
        /// </summary>
        public static string NumberArisesExists {
            get {
                return ResourceManager.GetString("NumberArisesExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberArisesNotValid.
        /// </summary>
        public static string NumberArisesNotValid {
            get {
                return ResourceManager.GetString("NumberArisesNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberArisesRequired.
        /// </summary>
        public static string NumberArisesRequired {
            get {
                return ResourceManager.GetString("NumberArisesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberFormatError.
        /// </summary>
        public static string NumberFormatError {
            get {
                return ResourceManager.GetString("NumberFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPDN.
        /// </summary>
        public static string OilImportCode {
            get {
                return ResourceManager.GetString("OilImportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentAdminSite.
        /// </summary>
        public static string ParentAdminSite {
            get {
                return ResourceManager.GetString("ParentAdminSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentID.
        /// </summary>
        public static string ParentID {
            get {
                return ResourceManager.GetString("ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumberFormatError.
        /// </summary>
        public static string PhoneNumberFormatError {
            get {
                return ResourceManager.GetString("PhoneNumberFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Info.
        /// </summary>
        public static string PriceInfo {
            get {
                return ResourceManager.GetString("PriceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceListed.
        /// </summary>
        public static string PriceListed {
            get {
                return ResourceManager.GetString("PriceListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Old.
        /// </summary>
        public static string PriceOld {
            get {
                return ResourceManager.GetString("PriceOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductRequired.
        /// </summary>
        public static string ProductRequired {
            get {
                return ResourceManager.GetString("ProductRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPKM.
        /// </summary>
        public static string PromotionCode {
            get {
                return ResourceManager.GetString("PromotionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish date.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishDetailLayout.
        /// </summary>
        public static string PublishDetailLayout {
            get {
                return ResourceManager.GetString("PublishDetailLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishDetailView.
        /// </summary>
        public static string PublishDetailView {
            get {
                return ResourceManager.GetString("PublishDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishIndexLayout.
        /// </summary>
        public static string PublishIndexLayout {
            get {
                return ResourceManager.GetString("PublishIndexLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishIndexView.
        /// </summary>
        public static string PublishIndexView {
            get {
                return ResourceManager.GetString("PublishIndexView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientName.
        /// </summary>
        public static string RecipientName {
            get {
                return ResourceManager.GetString("RecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientRequired.
        /// </summary>
        public static string RecipientRequired {
            get {
                return ResourceManager.GetString("RecipientRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientRequiredNumber.
        /// </summary>
        public static string RecipientRequiredNumber {
            get {
                return ResourceManager.GetString("RecipientRequiredNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportProduct.
        /// </summary>
        public static string ReportProduct {
            get {
                return ResourceManager.GetString("ReportProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredCommodityID.
        /// </summary>
        public static string RequiredCommodityID {
            get {
                return ResourceManager.GetString("RequiredCommodityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredCommodityName.
        /// </summary>
        public static string RequiredCommodityName {
            get {
                return ResourceManager.GetString("RequiredCommodityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredCommodityTax.
        /// </summary>
        public static string RequiredCommodityTax {
            get {
                return ResourceManager.GetString("RequiredCommodityTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredCustomerID.
        /// </summary>
        public static string RequiredCustomerID {
            get {
                return ResourceManager.GetString("RequiredCustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredCustomerName.
        /// </summary>
        public static string RequiredCustomerName {
            get {
                return ResourceManager.GetString("RequiredCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số tiền.
        /// </summary>
        public static string RequiredPrice {
            get {
                return ResourceManager.GetString("RequiredPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredPriceListed.
        /// </summary>
        public static string RequiredPriceListed {
            get {
                return ResourceManager.GetString("RequiredPriceListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredProduct.
        /// </summary>
        public static string RequiredProduct {
            get {
                return ResourceManager.GetString("RequiredProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredShopCode.
        /// </summary>
        public static string RequiredShopCode {
            get {
                return ResourceManager.GetString("RequiredShopCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredShopName.
        /// </summary>
        public static string RequiredShopName {
            get {
                return ResourceManager.GetString("RequiredShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredSupplierID.
        /// </summary>
        public static string RequiredSupplierID {
            get {
                return ResourceManager.GetString("RequiredSupplierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredSupplierName.
        /// </summary>
        public static string RequiredSupplierName {
            get {
                return ResourceManager.GetString("RequiredSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredTimeApply.
        /// </summary>
        public static string RequiredTimeApply {
            get {
                return ResourceManager.GetString("RequiredTimeApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter the Title.
        /// </summary>
        public static string RequiredTitle {
            get {
                return ResourceManager.GetString("RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter the Username.
        /// </summary>
        public static string RequiredUserName {
            get {
                return ResourceManager.GetString("RequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeoTitle.
        /// </summary>
        public static string SeoTitle {
            get {
                return ResourceManager.GetString("SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopCode.
        /// </summary>
        public static string ShopCode {
            get {
                return ResourceManager.GetString("ShopCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopCodeExists.
        /// </summary>
        public static string ShopCodeExists {
            get {
                return ResourceManager.GetString("ShopCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopID.
        /// </summary>
        public static string ShopID {
            get {
                return ResourceManager.GetString("ShopID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopNameExists.
        /// </summary>
        public static string ShopNameExists {
            get {
                return ResourceManager.GetString("ShopNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopName.
        /// </summary>
        public static string ShoprName {
            get {
                return ResourceManager.GetString("ShoprName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpendName.
        /// </summary>
        public static string SpendName {
            get {
                return ResourceManager.GetString("SpendName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpendRequired.
        /// </summary>
        public static string SpendRequired {
            get {
                return ResourceManager.GetString("SpendRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationRequired.
        /// </summary>
        public static string StationRequired {
            get {
                return ResourceManager.GetString("StationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubAdminSites.
        /// </summary>
        public static string SubAdminSites {
            get {
                return ResourceManager.GetString("SubAdminSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubQuerys.
        /// </summary>
        public static string SubQuerys {
            get {
                return ResourceManager.GetString("SubQuerys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubWebModules.
        /// </summary>
        public static string SubWebModules {
            get {
                return ResourceManager.GetString("SubWebModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierAddress.
        /// </summary>
        public static string SupplierAddress {
            get {
                return ResourceManager.GetString("SupplierAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierID.
        /// </summary>
        public static string SupplierID {
            get {
                return ResourceManager.GetString("SupplierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID is not exists.
        /// </summary>
        public static string SupplierIdExists {
            get {
                return ResourceManager.GetString("SupplierIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierName.
        /// </summary>
        public static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierRequired.
        /// </summary>
        public static string SupplierRequired {
            get {
                return ResourceManager.GetString("SupplierRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxCode.
        /// </summary>
        public static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxNumberFormatError.
        /// </summary>
        public static string TaxNumberFormatError {
            get {
                return ResourceManager.GetString("TaxNumberFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeApply.
        /// </summary>
        public static string TimeApply {
            get {
                return ResourceManager.GetString("TimeApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeNotValid.
        /// </summary>
        public static string TimeNotValid {
            get {
                return ResourceManager.GetString("TimeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalDiscount.
        /// </summary>
        public static string TotalDiscount {
            get {
                return ResourceManager.GetString("TotalDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalFreightCharge.
        /// </summary>
        public static string TotalFreightCharge {
            get {
                return ResourceManager.GetString("TotalFreightCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalMoney.
        /// </summary>
        public static string TotalMoney {
            get {
                return ResourceManager.GetString("TotalMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalQuantity.
        /// </summary>
        public static string TotalQuantity {
            get {
                return ResourceManager.GetString("TotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        public static string UID {
            get {
                return ResourceManager.GetString("UID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UintMoneyNotValid.
        /// </summary>
        public static string UintMoneyNotValid {
            get {
                return ResourceManager.GetString("UintMoneyNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is not valid.
        /// </summary>
        public static string UserNameNotValid {
            get {
                return ResourceManager.GetString("UserNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicles.
        /// </summary>
        public static string vehicles {
            get {
                return ResourceManager.GetString("vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web CategoryID.
        /// </summary>
        public static string WebCategoryID {
            get {
                return ResourceManager.GetString("WebCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebContacts.
        /// </summary>
        public static string WebContacts {
            get {
                return ResourceManager.GetString("WebContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Content ID.
        /// </summary>
        public static string WebContentID {
            get {
                return ResourceManager.GetString("WebContentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebContents.
        /// </summary>
        public static string WebContents {
            get {
                return ResourceManager.GetString("WebContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebModule.
        /// </summary>
        public static string WebModule {
            get {
                return ResourceManager.GetString("WebModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebModuleID.
        /// </summary>
        public static string WebModuleID {
            get {
                return ResourceManager.GetString("WebModuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weigh.
        /// </summary>
        public static string Weigh {
            get {
                return ResourceManager.GetString("Weigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo.
        /// </summary>
        public static string Yahoo {
            get {
                return ResourceManager.GetString("Yahoo", resourceCulture);
            }
        }
    }
}
